name: mobile_app_combine
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Для збереження налаштувань (токен, chat_id)
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^3.2.0
  firebase_database: ^11.1.0
  firebase_storage: ^12.1.0

  # Для роботи з Telegram API
  teledart: ^0.6.1
  logging: ^1.2.0

  # Для кастомних шрифтів (використовується в main.dart)
  google_fonts: ^6.2.1

  # Для форматування дати і часу
  intl: ^0.19.0

  # Іконки в стилі iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
