// lib/firebase_options.dart
// File generated by default, but we are creating it manually.
// You need to copy your own values here from the Firebase console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // ... other platforms
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- ВСТАВТЕ ВАШІ ДАНІ З FIREBASE CONSOLE СЮДИ ---
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBWHOg1tUdL5nGUFsNq4KuTjttToBE2QkQY", // <-- ВАШ КЛЮЧ
    appId: "1:597848779620:android:54c879e6499fb3b05ce871", // <-- ВАШ ID
    messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
    projectId: "projectcombain", // <-- ВАШ ID ПРОЄКТУ
    databaseURL:
        "https://projectcombain-default-rtdb.europe-west1.firebasedatabase.app/", // <-- ВАША URL БАЗИ ДАНИХ
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBWHOg1tUdL5nGUFsNq4KuTjttToBE2QkQY", // <-- ВАШ КЛЮЧ
    appId: "1:597848779620:ios:d72aafc6e047c7255ce871", // <-- ВАШ ID
    messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
    projectId: "projectcombain", // <-- ВАШ ID ПРОЄКТУ
    databaseURL:
        "https://projectcombain-default-rtdb.europe-west1.firebasedatabase.app/", // <-- ВАША URL БАЗИ ДАНИХ
    iosBundleId: 'com.example.myTestApp', // Переконайтесь, що це ваш bundle ID
  );
  // --------------------------------------------------
}
